### ISSUE TITLE
Changing the user agent 

### ISSUE THREAD

**Issue by ciex** [intolerable/reddit#24]
How can I change the user agent that this library uses for requests? 
The [Reddit API rules](https://github.com/reddit/reddit/wiki/API) require a unique and descriptive user agent string.

Thank you!

**Comment by tejon** [comment]
Use [`runRedditWith`](http://hackage.haskell.org/package/reddit-0.2.0.0/docs/Reddit.html#v:runRedditWith) instead of `runReddit`, and set the `customUserAgent` field in the [`RedditOptions`](http://hackage.haskell.org/package/reddit-0.2.0.0/docs/Reddit.html#t:RedditOptions) you supply as the first argument.

**Comment by ciex** [comment]
Thank you tejon. I suggest making a `customUserAgent` mandatory in order to comply with Reddit's API rules.

**Comment by tejon** [comment]
The documentation for (`runReddit`)[http://hackage.haskell.org/package/reddit-0.2.0.0/docs/Reddit.html#v:runReddit] does mention that you should change the UA. However, looking at the source now, there appears to be a bug... at the moment, I think the only way to successfully change your UA is to set it in a custom `Manager` and pass that in. [From what I see](https://github.com/intolerable/reddit/blob/master/src/Reddit.hs#L101-L114), the `customUserAgent` field is ignored completely; in the one case where it _might_ be used, a hard-coded string is used instead. Opening a separate bug for this.
